# Generated by Django 4.2.1 on 2023-05-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emplistuser',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='emplistuser',
            old_name='staff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='emplistuser',
            old_name='superuser',
            new_name='is_superuser',
        ),
    ]
