# Generated by Django 4.2.1 on 2023-05-19 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'CustomUser'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users_customuser',
        ),
    ]
