# Generated by Django 4.2 on 2023-04-05 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='支社番号')),
                ('name', models.CharField(max_length=100, verbose_name='支社名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('tel', models.CharField(max_length=11, verbose_name='電話番号')),
            ],
            options={
                'verbose_name': '支社',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='社員番号')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('post', models.CharField(max_length=100, null=True, verbose_name='役職')),
                ('date_of_entry', models.DateField(verbose_name='入社日')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='支社番号')),
            ],
        ),
    ]
