# Generated by Django 4.2.1 on 2023-05-26 02:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='支社名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('tel', models.CharField(max_length=11, verbose_name='電話番号')),
            ],
            options={
                'verbose_name': '支社',
                'verbose_name_plural': '支社一覧',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(19999)], verbose_name='社員番号')),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
                ('post', models.CharField(blank=True, max_length=30, null=True, verbose_name='役職')),
                ('date_of_entry', models.DateField(verbose_name='入社日')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_list_app.branch', verbose_name='支社番号')),
            ],
            options={
                'verbose_name': '社員',
                'verbose_name_plural': '社員一覧',
            },
        ),
    ]
