# Generated by Django 4.2 on 2023-04-05 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': '支社', 'verbose_name_plural': '支社一覧'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '社員', 'verbose_name_plural': '社員一覧'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_list_app.branch', verbose_name='支社番号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='役職'),
        ),
    ]
