# Generated by Django 4.2 on 2023-04-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_list_app', '0002_alter_branch_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=30, verbose_name='支社名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=30, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='役職'),
        ),
    ]
